"""
app.api.routers.ml
=====================

Task 6 — Machine Learning endpoints. Every response is read from artifacts
generated by the real training pipeline (``artifacts/``) or computed by a
cached, previously-trained pipeline. Nothing here is fabricated: if the
pipeline has not been run, these endpoints say so explicitly (404/503)
rather than inventing a number.
"""
from __future__ import annotations

import json

import pandas as pd
from fastapi import APIRouter, HTTPException

from app.core.paths import (
    ML_METRICS_DIR,
    ARTIFACT_MANIFEST_JSON,
)
from app.api.schemas import (
    LapTimePredictionRequest,
    LapTimePredictionResponse,
    PitPredictionRequest,
    PitPredictionResponse,
)
from app.intelligence.features.contract import load_feature_contract, load_feature_matrix
from app.intelligence.features.display import describe_features, feature_stats
from app.services.model_cache import ModelUnavailableError, get_model_cache

router = APIRouter(prefix="/api/ml", tags=["machine-learning"])


def _model_importance(target: str) -> tuple[str, dict[str, float]] | None:
    """(model_name, {feature: importance}) for the target's currently
    selected-best model, or None if that model has no native importance
    (e.g. SVM/SVR) or isn't available."""
    cache = get_model_cache()
    try:
        name, pipeline = cache.get_pipeline(target)
    except ModelUnavailableError:
        return None
    model = pipeline.named_steps["model"]
    names_raw = pipeline.named_steps["preprocess"].get_feature_names_out()
    names = [n.split("__", 1)[-1] for n in names_raw]
    if hasattr(model, "feature_importances_"):
        values = model.feature_importances_.tolist()
    elif hasattr(model, "coef_"):
        values = [abs(c) for c in model.coef_.ravel().tolist()]
    else:
        return name, {}
    return name, dict(zip(names, values))


def _read_json(path):
    if not path.exists():
        raise HTTPException(
            status_code=404,
            detail=f"No trained-model artifact at {path}. Run the training pipeline "
            "(scripts/build_all.py) to generate it.",
        )
    with open(path) as f:
        return json.load(f)


@router.get("/models")
def list_models():
    cache = get_model_cache()
    registry = cache.registry()
    if not registry:
        raise HTTPException(
            status_code=404,
            detail="No model registry found. Run the training pipeline (scripts/build_all.py) first.",
        )
    return registry


@router.get("/metrics")
def get_metrics():
    return {
        "regression": _read_json(ML_METRICS_DIR / "regression_metrics.json"),
        "classification": _read_json(ML_METRICS_DIR / "classification_metrics.json"),
    }


@router.get("/comparison")
def get_comparison():
    return _read_json(ML_METRICS_DIR / "model_comparison.json")


@router.get("/artifacts")
def get_artifacts():
    return _read_json(ARTIFACT_MANIFEST_JSON)


@router.get("/feature-importance")
def get_feature_importance():
    cache = get_model_cache()
    registry = cache.registry()
    if not registry:
        raise HTTPException(status_code=404, detail="No model registry found.")

    out = {}
    for target in ("target_laptime", "target_pit_next_lap"):
        best = next((m for m in registry["models"] if m["target"] == target and m["is_selected_best"]), None)
        if best is None:
            continue
        result = _model_importance(target)
        if result is None:
            continue
        name, importance = result
        if not importance:
            out[target] = {"model": name, "supported": False, "importance": None}
            continue
        out[target] = {"model": name, "supported": True, "importance": importance}
    return out


@router.get("/top-features")
def get_top_features(target: str, n: int = 8):
    """The ``n`` most important features for ``target``'s selected-best
    model, with human-readable names/descriptions — used by the Race
    Strategy Simulator's simplified "Top Features" tab.

    Ranking method: native feature importance of the currently selected
    model (``feature_importances_`` for tree ensembles, absolute
    coefficient magnitude for linear/logistic models). If the best model
    has neither (e.g. SVM/SVR), falls back to the *first n* features in the
    Task 5 selection order and says so explicitly — never a fabricated
    ranking.
    """
    if target not in ("target_laptime", "target_pit_next_lap"):
        raise HTTPException(status_code=422, detail="target must be 'target_laptime' or 'target_pit_next_lap'")

    contract = load_feature_contract()
    all_features = contract.selected_features(target)
    result = _model_importance(target)

    if result is not None and result[1]:
        model_name, importance = result
        ranked = sorted(all_features, key=lambda f: importance.get(f, 0.0), reverse=True)
        method = f"native feature importance of the selected-best model ({model_name})"
    else:
        model_name = result[0] if result else None
        ranked = all_features
        method = (
            f"the selected-best model ({model_name}) has no native feature importance "
            "(e.g. an SVM/SVR kernel) — falling back to Task 5's selection order, not a fabricated ranking"
        )

    top = ranked[:n]
    remaining = [f for f in all_features if f not in top]
    frame = load_feature_matrix()
    stats = feature_stats(all_features, frame)
    return {
        "target": target,
        "model": model_name,
        "ranking_method": method,
        "top_features": describe_features(top, contract, stats),
        "remaining_features": describe_features(remaining, contract, stats),
    }


@router.post("/predict/laptime", response_model=LapTimePredictionResponse)
def predict_laptime(request: LapTimePredictionRequest):
    contract = load_feature_contract()
    expected = set(contract.selected_features("target_laptime"))
    given = set(request.root.keys())
    if given != expected:
        raise HTTPException(
            status_code=422,
            detail={"error": "feature mismatch", "expected": sorted(expected), "missing": sorted(expected - given), "unexpected": sorted(given - expected)},
        )

    cache = get_model_cache()
    try:
        name, pipeline = cache.get_pipeline("target_laptime")
    except ModelUnavailableError as exc:
        raise HTTPException(status_code=503, detail=str(exc)) from exc

    X = pd.DataFrame([request.root])[contract.selected_features("target_laptime")]
    prediction = float(pipeline.predict(X)[0])

    return LapTimePredictionResponse(model=name, prediction=prediction, data_source=contract.dataset_source["source"])


@router.post("/predict/pit", response_model=PitPredictionResponse)
def predict_pit(request: PitPredictionRequest):
    contract = load_feature_contract()
    expected = set(contract.selected_features("target_pit_next_lap"))
    given = set(request.root.keys())
    if given != expected:
        raise HTTPException(
            status_code=422,
            detail={"error": "feature mismatch", "expected": sorted(expected), "missing": sorted(expected - given), "unexpected": sorted(given - expected)},
        )

    cache = get_model_cache()
    try:
        name, pipeline = cache.get_pipeline("target_pit_next_lap")
    except ModelUnavailableError as exc:
        raise HTTPException(status_code=503, detail=str(exc)) from exc

    X = pd.DataFrame([request.root])[contract.selected_features("target_pit_next_lap")]
    proba = float(pipeline.predict_proba(X)[0, 1])
    predicted_class = int(pipeline.predict(X)[0])

    return PitPredictionResponse(
        model=name, probability_pit=proba, predicted_class=predicted_class, data_source=contract.dataset_source["source"]
    )
